version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx
    networks:
      - nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - redis
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - nginx
    volumes:
      - redis_data:/data
    restart: always
volumes:
  redis_data:
networks:
  nginx:
    driver: bridge
